services:
  - type: web
    name: preklad-nemcina-web
    runtime: php
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT router.php
    envVars:
      - key: PHP_VERSION
        value: "8.2"
    healthCheckPath: /
